<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Android_SignUp</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1fc4c52d-ae12-401c-9c64-82758996ad45</testSuiteGuid>
   <testCaseLink>
      <guid>16add129-dd2b-4a34-91f1-1e4539b27ffa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Validation_cases/Android_SignUp - validateMessageforEmptyFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>087c19bd-c3bb-4743-9e0d-0065d10e3292</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92b7f1c0-3179-43d5-bcdf-cc5ce08e35e6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
